baseurl                 = "/"
relativeURLs            = true
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "NORMENT Early Career Researchers Meeting 2020"
theme                   = "sam"
pygmentsStyle           = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
publishDir              = "docs"

[markup.goldmark.renderer]
      unsafe = true

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "sam.ico"
    homepage            = "home"                           # What to call the home page link
    footerText          = "NORMENT Early Career Researchers Meeting 2020"

# Metadata for Open Graph and Twitter
    description         = "Interactive site for the Escape Room at the NORMENT Early-Career Researcher Meeting 2020"
    images              = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title               = "Open Science Escape Room"
    # rss               = ""

[[params.videoBackground.sources]]
    source  = "images/background_video.mp4"
    type    = "video/mp4"
    poster  = "images/background.jpg"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.6)" # optional

#[[params.mainMenu]]
#    link = "items/program"
#    text = "meeting program"
[[params.mainMenu]]
    link = "introduction"
    text = "start"
[[params.mainMenu]]
    link = "tasks"
    text = "tasks"
[[params.mainMenu]]
    link = "instructions"
    text = "instructions"
[[params.mainMenu]]
    link = "about"
    text = "about"

[imaging]
    quality = 75
